### ISSUE TITLE
State tab blank in Chrome

### ISSUE THREAD

**Issue by beeing** [anton-lunev/angular-state-inspector#17]
Hi, similar to #16, I'm experiencing this issue as well.

on Chrome Version 92.0.4515.107 (Official Build) (x86_64)

However the state still accessible via `$state` in console.

**Comment by rycastaneda** [comment]
experiencing this issue as well

**Comment by rpinco** [comment]
Same here, state inspector is blank on chromium based browsers as well, (Using Brave Version 1.27.108 Chromium: 92.0.4515.107 )

**Comment by thaoula** [comment]
Hi,

Yeah, I think this is the same I reported earlier and was closed #16 . 

It also still not working on newer versions Microsoft Edge - Version 93.0.957.0 (Official build) Dev(x86_64). 

Regards,
Tarek

**Comment by beeing** [comment]
Running in developer mode, I noticed there's this error when inspect on the element.

```
root.js:1 Uncaught (in promise) TypeError: Cannot read property '_loadPromise' of undefined
```

Possibly this is the cause.

**Comment by beeing** [comment]
Looks like this may be a bug on the browser itself while loading the extensions.

Hopefully newer version will work again.

**Comment by anavalaka** [comment]
same for me. anyone found a workaround?

**Comment by thaoula** [comment]
Hi @anavalaka ,

The only workaround is use $state as mentioned by @beeing. Basically select the html element in DevTools then in the console type $state

You will be able to view it there. Much better than nothing.

Regards,
Tarek

**Comment by andrei-ilyukovich** [comment]
Hi @anavalaka ,
there is pretty good tool provided by Angular team https://angular.io/guide/devtools, just check it out.

**Comment by beeing** [comment]
Tried the Angular DevTools, personally I still find this extension more usable as I can inspect the data for the selected element.

**Comment by slavede** [comment]
@beeing exactly what I think. What I miss from angular dev tools is inspection of state through elements tab...

**Comment by anton-lunev** [comment]
Thank you everyone, and sorry for the long response.
It turns that all tab extensions are broken in chromium browsers
https://bugs.chromium.org/p/chromium/issues/detail?id=1232063
So, unfortunately, all we can do is to wait for resolving this issue.

**Comment by anavalaka** [comment]
hello guys. anyone still remember a good chrome version we can rollback into?

**Comment by anton-lunev** [comment]
Hi @anavalaka, this issue is fixed in beta and canary versions. 
So you can install one of these till stable chrome v93 is not released.

**Comment by maleet** [comment]
I downloaded 
Microsoft Edge
Version 94.0.985.0 (Official build) canary (64-bit)

and there it's still not working

**Comment by rogerfar** [comment]
Reading that thread it looks like it's fixed in 93.0.4577.42, which can be downloaded right now from here: https://www.google.com/intl/en_ca/chrome/beta/

93 is supposed to go stable August 31st.

**Comment by axrl** [comment]
> hello guys. anyone still remember a good chrome version we can rollback into?

I am using Сhromium version 90.0.4430.0. Extension work for me on Windows and on my Mac.
I downloaded it [here](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/857997/)

**Comment by thaoula** [comment]
Can confirm this is now working on Microsoft Edge
Version 94.0.992.4 (Official build) Dev(x86_64)

**Comment by anton-lunev** [comment]
Stable Chrome 93 has been released, extension is fixed and tested. Closing issue.
